service: penn-station-scraper

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 180
  iamRoleStatements:
   -  Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::penn-station-nj-transit-departures/*"
   -  Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::penn-station-nj-transit-departures-screenshots/*"

functions:
  testFunction:
    handler: index.handler
    environment:
      DEBUG: 0
    events:
      - schedule: rate(1 minute)

package:
  artifact: ./package.zip
  
plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - npm run package