service: penn-station-scraper

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 180
  iamRoleStatements:
   -  Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::penn-station-nj-transit-departures/*"

functions:
  scrape:
    handler: index.scrape
    environment:
      DEBUG: 0

package:
  artifact: ./package.zip
  exclude:
    - coverage/**
    - .circleci/**
  
plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - npm run package