version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/PennStationNJTransit/src/penn-station-scraper

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run:
          name: Change to serverless directory within repo
          command: cd src/penn-station-scraper && pwd
      
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            pwd
            yarn install
      
      - run:
          name: Deploy application to development
          command:  cd src/penn-station-scraper && pwd && ls && SLS_DEBUG=* sls deploy -v
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
